# Generated by Django 5.2 on 2025-05-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='credentials',
            field=models.FileField(blank=True, help_text='Upload your certifications or credentials (PDF format)', null=True, upload_to='credentials/'),
        ),
        migrations.AddField(
            model_name='application',
            name='reference_letter',
            field=models.FileField(blank=True, help_text='Upload reference letters if available', null=True, upload_to='references/'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF or Word document)', null=True, upload_to='resumes/'),
        ),
    ]
