# Generated by Django 5.0.2 on 2025-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_credentials_application_reference_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
