from django.urls import path
from . import views

app_name = 'custom_admin'

from .views import integration_management

urlpatterns = [
    # Guide CRUD
    path('guides/', views.guide_list, name='guide_list'),
    path('guides/add/', views.guide_add, name='guide_add'),
    path('guides/edit/<int:guide_id>/', views.guide_edit, name='guide_edit'),
    path('guides/delete/<int:guide_id>/', views.guide_delete, name='guide_delete'),
    # FAQ CRUD
    path('faqs/', views.faq_list, name='faq_list'),
    path('faqs/add/', views.faq_add, name='faq_add'),
    path('faqs/edit/<int:faq_id>/', views.faq_edit, name='faq_edit'),
    path('faqs/delete/<int:faq_id>/', views.faq_delete, name='faq_delete'),
    path('login/', views.custom_admin_login, name='login'),
    path('videos/', views.video_list, name='video_list'),
    path('videos/add/', views.video_add, name='video_add'),
    path('videos/edit/<int:video_id>/', views.video_edit, name='video_edit'),
    path('videos/delete/<int:video_id>/', views.video_delete, name='video_delete'),
    path('articles/', views.article_list, name='article_list'),
    path('articles/add/', views.article_add, name='article_add'),
    path('articles/edit/<int:article_id>/', views.article_edit, name='article_edit'),
    path('articles/delete/<int:article_id>/', views.article_delete, name='article_delete'),
    path('links/', views.link_list, name='link_list'),
    path('links/add/', views.link_add, name='link_add'),
    path('links/edit/<int:link_id>/', views.link_edit, name='link_edit'),
    path('links/delete/<int:link_id>/', views.link_delete, name='link_delete'),
    path('slides/', views.slide_list, name='slide_list'),
    path('slides/add/', views.slide_add, name='slide_add'),
    path('slides/edit/<int:slide_id>/', views.slide_edit, name='slide_edit'),
    path('slides/delete/<int:slide_id>/', views.slide_delete, name='slide_delete'),
    path('tags/', views.tag_list, name='tag_list'),
    path('tags/add/', views.add_tag, name='add_tag'),
    path('tags/add-form/', views.tag_add, name='tag_add'),
    path('tags/edit/<int:tag_id>/', views.tag_edit, name='tag_edit'),
    path('tags/delete/<int:tag_id>/', views.tag_delete, name='tag_delete'),
    path('api/moderation/messages/', views.api_moderation_messages, name='api_moderation_messages'),
    path('api/moderation/replies/', views.api_moderation_replies, name='api_moderation_replies'),
    path('api/integrations/', views.integration_list, name='integration_list'),
    path('api/integrations/add/', views.integration_add, name='integration_add'),
    path('api/integrations/<int:pk>/edit/', views.integration_edit, name='integration_edit'),
    path('api/download_logs/', views.download_logs, name='download_logs'),
    path('api/clear_cache/', views.clear_cache, name='clear_cache'),
    path('api/backup_database/', views.backup_database, name='backup_database'),
    path('api/restore_database/', views.restore_database, name='restore_database'),
    path('jobs/', views.job_list, name='job_list'),
path('notifications/', views.notification_list, name='notification_list'),
path('jobs/add/', views.job_create, name='job_add'),
path('jobs/edit/<int:job_id>/', views.job_edit, name='job_edit'),
path('jobs/delete/<int:job_id>/', views.job_delete, name='job_delete'),
path('jobs/<int:job_id>/detail/', views.job_detail, name='job_detail'),
path('jobs/<int:job_id>/apply/', views.apply_for_job, name='apply_for_job'),
path('applications/<int:application_id>/accept/', lambda request, application_id: views.update_application_status(request, application_id, 'accepted'), name='application_accept'),
path('applications/<int:application_id>/reject/', lambda request, application_id: views.update_application_status(request, application_id, 'rejected'), name='application_reject'),
    path('events/<int:event_id>/view/', views.event_view, name='event_view'),
    path('residents/', views.resident_management, name='resident_management'),
    path('accounts/CaregiverVerification/', views.caregiver_verification_list, name='caregiver_verification_list'),
    path('users/<int:user_id>/role_permission/', views.user_role_permission_edit, name='user_role_permission_edit'),
    path('', views.dashboard, name='dashboard'),
    path('integrations/', integration_management, name='integration_management'),
    path('maintenance/', views.maintenance_management, name='maintenance_management'),
    path('users/', views.user_management, name='user_management'),
    path('users/export/', views.export_users_csv, name='export_users_csv'),
    path('content/', views.content_management, name='content_management'),
    path('events/', views.event_management, name='event_management'),
    path('events/export/', views.export_events_csv, name='export_events_csv'),
    path('notifications/', views.notification_management, name='notification_management'),
    path('reporting/', views.reporting, name='reporting'),
    path('communication/', views.communication_oversight, name='communication_oversight'),
    path('billing/', views.billing_controls, name='billing_controls'),
    path('users/import/', views.user_import, name='user_import'),
    path('users/<int:user_id>/impersonate/', views.impersonate_user, name='impersonate_user'),
    path('impersonation/stop/', views.stop_impersonation, name='stop_impersonation'),
    path('events/import/', views.event_import, name='event_import'),
    path('api/notification_template/<int:id>/', views.notification_template_api, name='notification_template_api'),
    path('security/', views.security_compliance, name='security_compliance'),
    path('security/export/', views.export_audit_logs_csv, name='export_audit_logs_csv'),
    path('customization_settings/', views.customization_settings, name='customization_settings'),
    path('api/health_status/', views.api_get_health_status, name='api_get_health_status'),
]
