# Generated by Django 5.2 on 2025-05-05 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='OpenAI API Key', max_length=255)),
                ('model', models.CharField(default='gpt-4o-mini', help_text='OpenAI model to use', max_length=50)),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='chatbotlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chatbot Log', 'verbose_name_plural': 'Chatbot Logs'},
        ),
        migrations.AlterField(
            model_name='chatbotlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
