# Generated by Django 5.0.2 on 2025-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
