# Generated by Django 5.2 on 2025-05-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '000X_add_moderation_fields_to_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='moderation_notes',
        ),
    ]
