# Generated by Django 5.2.1 on 2025-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiververification',
            name='certification_type',
            field=models.CharField(blank=True, choices=[('nursing', 'Nursing Certificate'), ('elderly_care', 'Elderly Care Certification'), ('first_aid', 'First Aid/CPR'), ('medical_assistant', 'Medical Assistant'), ('other', 'Other')], max_length=100),
        ),
    ]
