# Generated by Django 5.2 on 2025-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_address_remove_user_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this caregiver has been verified by an admin.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('elderly', 'Elderly'), ('caregiver', 'Caregiver'), ('family', 'Family Member'), ('admin', 'Administrator')], default='elderly', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Asia/Kathmandu', 'Nepal Time'), ('Asia/Kolkata', 'India Time'), ('US/Eastern', 'US Eastern Time'), ('US/Pacific', 'US Pacific Time'), ('Europe/London', 'UK Time')], default='UTC', max_length=50),
        ),
    ]
