# Generated by Django 5.2 on 2025-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountdeletionrequest_is_pending_deletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdeletionrequest',
            name='is_pending_deletion',
        ),
        migrations.RemoveField(
            model_name='accountdeletionrequest',
            name='scheduled_deletion_at',
        ),
        migrations.AddField(
            model_name='user',
            name='is_pending_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
