# Generated by Django 5.0.2 on 2025-05-12 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_accountdeletionrequest_is_pending_deletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_id_number', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('certification_type', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='caregiver_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
