# Generated by Django 4.2.20 on 2025-05-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number in international format (e.g., +14155552671)', max_length=20, null=True),
        ),
    ]
