# Generated by Django 5.2 on 2025-05-14 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('time_of_day', models.TimeField()),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('browser', 'Browser')], default='email', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
