# Generated by Django 5.2.1 on 2025-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='homepage_slides/')),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower comes first')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
