# Generated by Django 5.2 on 2025-05-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_contactmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS to inject site-wide.')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('cta', 'Call To Action'), ('custom_html', 'Custom HTML')], default='text', max_length=50)),
                ('content', models.TextField(help_text='Content (rich text supported)')),
                ('style', models.JSONField(blank=True, default=dict, help_text='Per-block CSS or options as JSON')),
                ('is_visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='custom_admin.dynamicpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
