# Generated by Django 5.2 on 2025-05-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_homepageslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_slides/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='custom_admin.homepageslide')),
            ],
            options={
                'verbose_name': 'Homepage Slide Image',
                'verbose_name_plural': 'Homepage Slide Images',
                'ordering': ['order'],
            },
        ),
    ]
