# Generated by Django 5.2 on 2025-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_dynamicpage_themesetting_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='block_title',
            field=models.CharField(blank=True, help_text='Optional title/heading for this block', max_length=200),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_style',
            field=models.CharField(blank=True, help_text='Button style class(es)', max_length=100),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_text',
            field=models.CharField(blank=True, help_text='Text for button/link', max_length=100),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='button_url',
            field=models.URLField(blank=True, help_text='URL for button/link'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='collapsible',
            field=models.BooleanField(default=False, help_text='Make this block collapsible/expandable'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='condition',
            field=models.CharField(blank=True, help_text='Condition for display (e.g., user_logged_in)', max_length=100),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='html_tag',
            field=models.CharField(blank=True, default='div', help_text='HTML tag for this block (div, section, article, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional icon for this block', null=True, upload_to='block_icons/'),
        ),
    ]
