# Generated by Django 5.2 on 2025-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_contentblock_block_title_contentblock_button_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set this theme as the active site-wide theme.'),
        ),
    ]
