# Generated by Django 5.2 on 2025-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_sitetheme_delete_themesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetheme',
            name='selected_theme',
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('blue', 'Blue'), ('green', 'Green')], default='light', max_length=20, unique=True),
        ),
    ]
