# Generated by Django 5.0.2 on 2025-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_remove_sitetheme_selected_theme_sitetheme_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_theme', models.CharField(choices=[('light', 'Light'), ('blue', 'Blue'), ('green', 'Green'), ('dark', 'Dark')], default='light', max_length=20)),
            ],
            options={
                'verbose_name': 'Theme Setting',
                'verbose_name_plural': 'Theme Setting',
            },
        ),
        migrations.DeleteModel(
            name='SiteTheme',
        ),
    ]
