# Generated by Django 5.0.2 on 2025-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_themesetting_delete_sitetheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesetting',
            options={},
        ),
        migrations.RemoveField(
            model_name='themesetting',
            name='selected_theme',
        ),
        migrations.AddField(
            model_name='themesetting',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS to inject site-wide.'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='font_family',
            field=models.CharField(default='Inter, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='name',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
    ]
